### ISSUE TITLE
Gradle build fails on initializr generated project

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm-pack-spring#133]
Running latest uhura from master fails with:

```
TypeError: Cannot read property 'value' of undefined
    at /Users/ryan/dev/github/atomist/uhura/node_modules/@atomist/sdm-pack-spring/lib/gradle/parse/buildGradleParser.ts:35:74
    at Generator.next ()
    at fulfilled (/Users/ryan/dev/github/atomist/uhura/node_modules/@atomist/sdm-pack-spring/lib/gradle/parse/buildGradleParser.js:19:58)
    at 
04/15/2019 05:48:33.887    ERROR: Failure in executing goal:  Caused by: Cannot read property 'value' of undefined
```

for this project: https://github.com/fc-test/sbg-demo

**Comment by cdupuis** [comment]
This is now fixed.
